package com.dao;

import java.util.Date;

// Generated Jan 19, 2010 4:08:57 PM by Hibernate Tools 3.2.5.Beta

/**
 * Stock generated by hbm2java
 */
public class RadioShow implements java.io.Serializable {

	private long showId;
	private String title;
	private String description;
	private int archiveListens;
	private int liveListens;
	private Date listedDate;
	
	public RadioShow(String title, String description, int archiveListens, int liveListens, Date listedDate, long theShowId) {
		this.title=title;
		this.description=description;
		this.archiveListens=archiveListens;
		this.liveListens=liveListens;
		this.listedDate=listedDate;
		this.showId=theShowId;
	}
	
	public RadioShow() {
		
	}
	
	public long getShowId() {
		return showId;
	}
	public void setShowId(long showId) {
		this.showId = showId;
	}
	public String getTitle() {
		return title;
	}
	public void setTitle(String title) {
		this.title = title;
	}
	public String getDescription() {
		return description;
	}
	public void setDescription(String description) {
		this.description = description;
	}
	public int getArchiveListens() {
		return archiveListens;
	}
	public void setArchiveListens(int archiveListens) {
		this.archiveListens = archiveListens;
	}
	public int getLiveListens() {
		return liveListens;
	}
	public void setLiveListens(int liveListens) {
		this.liveListens = liveListens;
	}
	public Date getListedDate() {
		return listedDate;
	}
	public void setListedDate(Date listedDate) {
		this.listedDate = listedDate;
	}


	 @Override 
	 /**
	  * Used for displaying the student radio show information.  This is called
	  * from the logic iterate tag to display the desired radio show information.
	  * @return a string that identifies the radio show.
	  */
	 public String toString() {
		 return("Title:" + getTitle());
	 }


	
}
