package com.dao;

// Generated Jan 19, 2010 4:08:57 PM by Hibernate Tools 3.2.5.Beta

import java.util.Date;

/**
 * StockDetail generated by hbm2java
 */
public class ShowDetail implements java.io.Serializable {

	private Integer showId;
	private RadioShow radioShow;
	private Integer archiveListens;
	private Integer liveListens;
	private String description;

	private Date listedDate;

	public ShowDetail() {
	}

	public ShowDetail(RadioShow stock,  String compDesc,
			Integer archiveListens, Date listedDate) {
		this.radioShow = stock;
		this.description = compDesc;
		this.listedDate = listedDate;
		this.archiveListens = archiveListens;
	}



	public Date getListedDate() {
		return this.listedDate;
	}

	public void setListedDate(Date listedDate) {
		this.listedDate = listedDate;
	}
	public RadioShow getRadioShow() {
		return radioShow;
	}

	public void setRadioShow(RadioShow radioShow) {
		this.radioShow = radioShow;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}
	public Integer getArchiveListens() {
		return archiveListens;
	}

	public void setArchiveListens(Integer archiveListens) {
		this.archiveListens = archiveListens;
	}

	public Integer getLiveListens() {
		return liveListens;
	}

	public void setLiveListens(Integer liveListens) {
		this.liveListens = liveListens;
	}

	public Integer getShowId() {
		return showId;
	}

	public void setShowId(Integer showId) {
		this.showId = showId;
	}
	
	
}
